name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build, run, and test.
    runs-on: ubuntu-latest

    steps:
    - name: checkout workspace
      uses: actions/checkout@v2

    - name: Build docker image
      run: make build

    - name: Run docker image
      run: make run
